name: Pipeline Execution
on: [push]
jobs:
  runs-on: ubuntu-latest
  container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2

      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          dvc repro
          
          git fetch --prune
          dvc metrics diff --show-md main

          echo "## Validating Results by Region" >> report.md
          cml-publish by_region.png --md >> report.md
          cml-send-comment report.md